chore: workaround intermittent docker error on multiplatform tests (#1763)
Attempting to workaround intermittent failures in the `shells/default` test in the multiplatform run by disabling containerd-snapshotter, referenced in an upstream bug report (https://github.com/moby/moby/issues/52411).  The bug report is not an exact match for our configuration, but so far I haven't seen a failure with this change in-place.

The failure occurring is:
```
runner_test.go:225: Error Trace: /home/runner/.cache/act/d3be43f9a1663dbf/hostexecutor/act/runner/runner_test.go:225
failed to create container: Error response from daemon: apply layer error for "": failed to extract layer sha256:1b349a3334531b575b01d409540dd8aca14ef29abddacd50f36643d7c949db4b: NotFound: failed to get reader from content store: content digest sha256:a9986cd6f37dbddae7862a6d4be71683472e7c2ea708e87db14f8a6393c00f00: not found
Test: TestRunner_RunEvent/shells/defaults
Messages: /home/runner/.cache/act/d3be43f9a1663dbf/hostexecutor/act/runner/testdata/shells/defaults
```

Incidentally, fix that opening a PR with run-multi-platform-tests doesn't run the tests.

Reviewed-on: https://code.forgejo.org/forgejo/runner/pulls/1763
Reviewed-by: Andreas Ahlenstorf <aahlenst@noreply.code.forgejo.org>