test: allow overriding the test Docker socket using DOCKER_HOST (#1155)
My workstation uses Fedora 43 with rootless Podman. Unfortunately, the Runner test suite does not pick up the environment variable `DOCKER_HOST`. So I'm unable to run any tests that require Docker because it tries to use `/var/run/docker.sock`. With this change, I'm at least able to run some tests as long as I set `DOCKER_HOST`.

Normal Runner commands seem to work with Podman because they resolve the correct socket much earlier than some parts of the test suite.

Before:

```
> DOCKER_HOST=unix:///run/user/1000/podman/podman.sock go test -count=1 -run='TestRunner_RunEvent$/runs-on$' ./act/runner
...
--- FAIL: TestRunner_RunEvent (0.18s)
    --- FAIL: TestRunner_RunEvent/runs-on (0.18s)
        runner_test.go:211:
            	Error Trace:	/home/andreas/Projects/forgejo/runner/act/runner/runner_test.go:211
            	            				/home/andreas/Projects/forgejo/runner/act/runner/runner_test.go:369
            	Error:      	Received unexpected error:
            	            	failed to create container: 'Error response from daemon: container create: statfs /var/run/docker.sock: permission denied'
            	Test:       	TestRunner_RunEvent/runs-on
            	Messages:   	/home/andreas/Projects/forgejo/runner/act/runner/testdata/runs-on
FAIL
FAIL	code.forgejo.org/forgejo/runner/v11/act/runner	0.190s
FAIL

```

After:

```
> DOCKER_HOST=unix:///run/user/1000/podman/podman.sock go test -count=1 -run='TestRunner_RunEvent$/runs-on$' ./act/runner
ok  	code.forgejo.org/forgejo/runner/v11/act/runner	14.879s
```

<!--start release-notes-assistant-->
<!--URL:https://code.forgejo.org/forgejo/runner-->
- bug fixes
  - [PR](https://code.forgejo.org/forgejo/runner/pulls/1155): <!--number 1155 --><!--line 0 --><!--description Zml4OiBhbGxvdyBvdmVycmlkaW5nIHRoZSBEb2NrZXIgc29ja2V0IHVzaW5nIERPQ0tFUl9IT1NU-->fix: allow overriding the Docker socket using DOCKER_HOST<!--description-->
<!--end release-notes-assistant-->

Reviewed-on: https://code.forgejo.org/forgejo/runner/pulls/1155
Reviewed-by: Mathieu Fenniak <mfenniak@noreply.code.forgejo.org>
Co-authored-by: Andreas Ahlenstorf <andreas@ahlenstorf.ch>
Co-committed-by: Andreas Ahlenstorf <andreas@ahlenstorf.ch>